## Airport Simulation - 3 Servers 1 Queue & 3 Servers 3 Queues

Here this simulation is a 2 Process Simulation where we enter a process A(Check In) and the when that is complete we enter the 2nd Process B(Immigration). The CheckIn is a random distribution from value 3 to 7 min and Immigration is a normal distribution with a mean of 7 min and std dev with 2 mins. The checkin process has 3 servers which deal with it but only a single queue whereas after being finished with the checkin process they go into category based queues. There are 3 categories A B C all of which have a specific server

In [1]:
from random import randrange
import datetime
import random

In [2]:
def generateCategory():
    return random.choice('ABC')

In [3]:
def random_date(start, end):
    """
    This function will return a random datetime between two datetime 
    objects.
    """
    delta = end - start
    int_delta = (delta.days * 24 * 60 * 60) + delta.seconds
    random_second = randrange(int_delta)
    return start + datetime.timedelta(seconds=random_second)

In [4]:
d1 = datetime.datetime.strptime('1/1/2009 9:00 AM', '%m/%d/%Y %I:%M %p')
d2 = datetime.datetime.strptime('1/1/2009 10:30 AM', '%m/%d/%Y %I:%M %p')


N = 50
arrival_times = []
category = []

for i in range(N):
    arrival_times.append(random_date(d1, d2))
    category.append(generateCategory())
    
print(arrival_times[:5])
print(category[:5])

[datetime.datetime(2009, 1, 1, 9, 51, 12), datetime.datetime(2009, 1, 1, 9, 40, 50), datetime.datetime(2009, 1, 1, 10, 24, 26), datetime.datetime(2009, 1, 1, 9, 19, 14), datetime.datetime(2009, 1, 1, 10, 10, 17)]
['C', 'A', 'C', 'C', 'B']

In [5]:
import pandas as pd
import numpy as np


df = pd.DataFrame()
df['Passengers'] = list(np.arange(N) + 1)
df['Airport Arrival Time'] = arrival_times
df['Airport Arrival Time'] = df['Airport Arrival Time'].sort_values(ascending=True).tolist()
df['Category'] = category

df

    Passengers Airport Arrival Time Category
0            1  2009-01-01 09:02:01        C
1            2  2009-01-01 09:04:24        A
2            3  2009-01-01 09:04:41        C
3            4  2009-01-01 09:06:55        C
4            5  2009-01-01 09:07:25        B
5            6  2009-01-01 09:08:33        B
6            7  2009-01-01 09:08:53        A
7            8  2009-01-01 09:09:05        B
8            9  2009-01-01 09:11:40        C
9           10  2009-01-01 09:15:30        C
10          11  2009-01-01 09:17:19        B
11          12  2009-01-01 09:17:42        C
12          13  2009-01-01 09:19:11        B
13          14  2009-01-01 09:19:14        C
14          15  2009-01-01 09:19:30        A
15          16  2009-01-01 09:28:11        B
16          17  2009-01-01 09:30:03        A
17          18  2009-01-01 09:30:35        C
18          19  2009-01-01 09:31:12        A
19          20  2009-01-01 09:31:13        C
20          21  2009-01-01 09:32:20        B
21          22  2009-01-01 09:33:46        A
22          23  2009-01-01 09:35:13        A
23          24  2009-01-01 09:35:56        B
24          25  2009-01-01 09:36:17        A
25          26  2009-01-01 09:37:01        C
26          27  2009-01-01 09:40:50        B
27          28  2009-01-01 09:41:38        A
28          29  2009-01-01 09:42:44        A
29          30  2009-01-01 09:48:35        B
30          31  2009-01-01 09:48:53        A
31          32  2009-01-01 09:50:17        B
32          33  2009-01-01 09:50:34        A
33          34  2009-01-01 09:50:45        A
34          35  2009-01-01 09:51:12        A
35          36  2009-01-01 10:02:52        A
36          37  2009-01-01 10:03:38        C
37          38  2009-01-01 10:06:12        A
38          39  2009-01-01 10:07:04        C
39          40  2009-01-01 10:08:33        C
40          41  2009-01-01 10:08:54        C
41          42  2009-01-01 10:10:17        C
42          43  2009-01-01 10:11:03        B
43          44  2009-01-01 10:18:12        A
44          45  2009-01-01 10:19:20        C
45          46  2009-01-01 10:23:08        B
46          47  2009-01-01 10:23:30        C
47          48  2009-01-01 10:24:26        B
48          49  2009-01-01 10:27:17        B
49          50  2009-01-01 10:28:28        B

In [6]:
df.dtypes

Passengers                       int64
Airport Arrival Time    datetime64[ns]
Category                        object
dtype: object

In [7]:
def time2timedelta(timeObj):
    return datetime.datetime.combine(datetime.date.min, timeObj) - datetime.datetime.min

def timedelta2time(deltaObj):
    return (datetime.datetime.min + deltaObj).time()

In [8]:
import math

def checkIn_process(low_val, high_val):
    random_number = np.random.uniform(low=low_val, high=high_val)
    hours = math.floor(random_number/60)
    minutes = math.floor(random_number) if random_number < 60 else (math.floor(random_number) - (hours*60))
    seconds = round(((random_number - math.floor(random_number))*0.6)*100)
    x = timedelta2time(datetime.timedelta(hours = hours, minutes = minutes, seconds = seconds))
    return x 

low_val = 3.0
high_val = 7.0


def immigration_Process(mu, sigma):
    random_number = np.random.normal(mu, sigma)
    hours = math.floor(random_number/60)
    minutes = math.floor(random_number) if random_number < 60 else (math.floor(random_number) - (hours*60))
    seconds = round(((random_number - math.floor(random_number))*0.6)*100)
    x = timedelta2time(datetime.timedelta(hours = hours, minutes = minutes, seconds = seconds))
    return x 

mu = 8
sigma = 2

In [9]:
checkin_queue, checkin_start, checkin_process, checkin_finish, checkin_waited = [], [], [], [], []
immigration_queue, immigration_start, immigration_process, immigration_finish, immigration_waited = [], [], [], [], []
total_time = []

In [10]:
checkin_queue.append(timedelta2time(datetime.timedelta(seconds=0)))
checkin_start.append(df['Airport Arrival Time'][0].to_pydatetime())

checkinProcess = checkIn_process(low_val, high_val)
checkin_process.append(checkinProcess)

checkinFinish = checkin_start[0] + time2timedelta(checkin_process[0]) 
checkin_finish.append(checkinFinish)


immigration_queue.append(timedelta2time(datetime.timedelta(seconds=0)))
immigration_start.append(checkin_finish[0])

immigrationProcess = immigration_Process(mu, sigma)
immigration_process.append(immigrationProcess)

immigrationFinish = immigration_start[0] + time2timedelta(immigration_process[0]) 
immigration_finish.append(immigrationFinish)



checkin_server_times = [checkin_finish[-1], df['Airport Arrival Time'][0].to_pydatetime(), df['Airport Arrival Time'][0].to_pydatetime()]
checkin_server_assigned = []
checkin_server_assigned.append(1)

A_queue, B_queue, C_queue = [], [], []

if df['Category'][0] == 'A':
    A_queue.append(immigration_finish[-1])
    B_queue.append(df['Airport Arrival Time'][0].to_pydatetime())
    C_queue.append(df['Airport Arrival Time'][0].to_pydatetime())
elif df['Category'][0] == 'B':
    A_queue.append(df['Airport Arrival Time'][0].to_pydatetime())
    B_queue.append(immigration_finish[-1])
    C_queue.append(df['Airport Arrival Time'][0].to_pydatetime())
else:
    A_queue.append(df['Airport Arrival Time'][0].to_pydatetime())
    B_queue.append(df['Airport Arrival Time'][0].to_pydatetime())
    C_queue.append(immigration_finish[-1])
    


total_time.append(timedelta2time(immigration_finish[-1] - checkin_start[-1]))

In [11]:
for index, row in df.iterrows():
    if index == 0:
        continue
    checkin_arrivalTime = df['Airport Arrival Time'][index].to_pydatetime()
    
    server, tobe_server = -1, -1
    
    # 1 queue and 3 servers 
    
    for i in range(3):
        if checkin_server_times[i]!=0 and (checkin_arrivalTime < checkin_server_times[i]):
            tobe_server = np.argmin(checkin_server_times)
        else:
            server = i
            break
            
    if server!= -1: #There is a free server
        checkin_queue.append(timedelta2time(datetime.timedelta(seconds=0)))
        checkin_start.append(checkin_arrivalTime)
        
        checkinProcess = checkIn_process(low_val, high_val)
        checkin_process.append(checkinProcess)
        
        checkinFinish = checkin_start[-1] + time2timedelta(checkin_process[-1]) 
        checkin_finish.append(checkinFinish)
        
        checkin_waited.append(timedelta2time(checkinFinish - checkin_arrivalTime))
        
        checkin_server_assigned.append(server+1)
        checkin_server_times[server] = checkin_finish[-1]
    else:
        checkin_queue.append(timedelta2time(checkin_server_times[tobe_server] - checkin_arrivalTime))
        checkin_start.append(checkin_server_times[tobe_server])
        
        checkinProcess = checkIn_process(low_val, high_val)
        checkin_process.append(checkinProcess)
        
        checkinFinish = checkin_start[-1] + time2timedelta(checkin_process[-1])
        checkin_finish.append(checkinFinish)
        
        checkin_waited.append(timedelta2time(checkinFinish - checkin_arrivalTime))
        
        checkin_server_assigned.append(tobe_server+1)
        checkin_server_times[tobe_server] = checkin_finish[-1]
    
    # 3 Servers with 3 distinct queues based on the category of the person
    
    if df['Category'][index] == 'A':
        if checkin_finish[-1] >= A_queue[-1]: # The queue for A is empty
            immigration_start.append(checkin_finish[-1])
            immigration_queue.append(timedelta2time(datetime.timedelta(seconds=0)))
        else:
            immigration_start.append(A_queue[-1])
            immigration_queue.append(timedelta2time(A_queue[-1] - checkin_finish[-1]))
        
        immigrationProcess = immigration_Process(mu, sigma)
        immigration_process.append(immigrationProcess)

        immigrationFinish = immigration_start[-1] + time2timedelta(immigration_process[-1]) 
        immigration_finish.append(immigrationFinish)
        
        A_queue.append(immigrationFinish)
        
        
    elif df['Category'][index] == 'B':
        if checkin_finish[-1] >= B_queue[-1]: # The queue for B is empty
            immigration_start.append(checkin_finish[-1])
            immigration_queue.append(timedelta2time(datetime.timedelta(seconds=0)))
        else:
            immigration_start.append(B_queue[-1])
            immigration_queue.append(timedelta2time(B_queue[-1] - checkin_finish[-1]))
            
        immigrationProcess = immigration_Process(mu, sigma)
        immigration_process.append(immigrationProcess)

        immigrationFinish = immigration_start[-1] + time2timedelta(immigration_process[-1]) 
        immigration_finish.append(immigrationFinish)
        
        B_queue.append(immigrationFinish)
    else:
        if checkin_finish[-1] >= C_queue[-1]: # The queue for C is empty
            immigration_start.append(checkin_finish[-1])
            immigration_queue.append(timedelta2time(datetime.timedelta(seconds=0)))
        else:
            immigration_start.append(C_queue[-1])
            immigration_queue.append(timedelta2time(C_queue[-1] - checkin_finish[-1]))
            
        immigrationProcess = immigration_Process(mu, sigma)
        immigration_process.append(immigrationProcess)

        immigrationFinish = immigration_start[-1] + time2timedelta(immigration_process[-1]) 
        immigration_finish.append(immigrationFinish)
        
        C_queue.append(immigrationFinish)
        
    total_time.append(timedelta2time(immigration_finish[-1] - checkin_arrivalTime))

In [12]:
df['Check-In Queue Time'] = checkin_queue
df['Check-In Start Time'] = checkin_start
df['Check-In Process Time'] = checkin_process
df['Check-In Finish Time'] = checkin_finish
df['Check-In Server Assigned'] = checkin_server_assigned

df['Immigration Queue Time'] = immigration_queue
df['Immigration Start Time'] = immigration_start
df['Immigration Process Time'] = immigration_process
df['Immigration Finish Time'] = immigration_finish

df['Total Time Spent'] = total_time

df

,Passengers,Airport Arrival Time,Category,Check-In Queue Time,Check-In Start Time,Check-In Process Time,Check-In Finish Time,Check-In Server Assigned,Immigration Queue Time,Immigration Start Time,Immigration Process Time,Immigration Finish Time,Total Time Spent
0,1,2009-01-01 09:02:01,C,00:00:00,2009-01-01 09:02:01,00:04:05,2009-01-01 09:06:06,1,00:00:00,2009-01-01 09:06:06,00:10:13,2009-01-01 09:16:19,00:14:18
1,2,2009-01-01 09:04:24,A,00:00:00,2009-01-01 09:04:24,00:05:06,2009-01-01 09:09:30,2,00:00:00,2009-01-01 09:09:30,00:09:52,2009-01-01 09:19:22,00:14:58
2,3,2009-01-01 09:04:41,C,00:00:00,2009-01-01 09:04:41,00:06:25,2009-01-01 09:11:06,3,00:05:13,2009-01-01 09:16:19,00:08:25,2009-01-01 09:24:44,00:20:03
3,4,2009-01-01 09:06:55,C,00:00:00,2009-01-01 09:06:55,00:03:12,2009-01-01 09:10:07,1,00:14:37,2009-01-01 09:24:44,00:08:58,2009-01-01 09:33:42,00:26:47
4,5,2009-01-01 09:07:25,B,00:02:05,2009-01-01 09:09:30,00:06:32,2009-01-01 09:16:02,2,00:00:00,2009-01-01 09:16:02,00:10:08,2009-01-01 09:26:10,00:18:45
5,6,2009-01-01 09:08:33,B,00:01:34,2009-01-01 09:10:07,00:04:35,2009-01-01 09:14:42,1,00:11:28,2009-01-01 09:26:10,00:05:59,2009-01-01 09:32:09,00:23:36
6,7,2009-01-01 09:08:53,A,00:02:13,2009-01-01 09:11:06,00:06:03,2009-01-01 09:17:09,3,00:02:13,2009-01-01 09:19:22,00:12:00,2009-01-01 09:31:22,00:22:29
7,8,2009-01-01 09:09:05,B,00:05:37,2009-01-01 09:14:42,00:06:14,2009-01-01 09:20:56,1,00:11:13,2009-01-01 09:32:09,00:09:21,2009-01-01 09:41:30,00:32:25
8,9,2009-01-01 09:11:40,C,00:04:22,2009-01-01 09:16:02,00:05:20,2009-01-01 09:21:22,2,00:12:20,2009-01-01 09:33:42,00:08:41,2009-01-01 09:42:23,00:30:43
9,10,2009-01-01 09:15:30,C,00:01:39,2009-01-01 09:17:09,00:06:20,2009-01-01 09:23:29,3,00:18:54,2009-01-01 09:42:23,00:10:12,2009-01-01 09:52:35,00:37:05
10,11,2009-01-01 09:17:19,B,00:03:37,2009-01-01 09:20:56,00:03:07,2009-01-01 09:24:03,1,00:17:27,2009-01-01 09:41:30,00:05:32,2009-01-01 09:47:02,00:29:43
11,12,2009-01-01 09:17:42,C,00:03:40,2009-01-01 09:21:22,00:06:30,2009-01-01 09:27:52,2,00:24:43,2009-01-01 09:52:35,00:06:20,2009-01-01 09:58:55,00:41:13
12,13,2009-01-01 09:19:11,B,00:04:18,2009-01-01 09:23:29,00:05:32,2009-01-01 09:29:01,3,00:18:01,2009-01-01 09:47:02,00:05:10,2009-01-01 09:52:12,00:33:01
13,14,2009-01-01 09:19:14,C,00:04:49,2009-01-01 09:24:03,00:05:00,2009-01-01 09:29:03,1,00:29:52,2009-01-01 09:58:55,00:10:15,2009-01-01 10:09:10,00:49:56
14,15,2009-01-01 09:19:30,A,00:08:22,2009-01-01 09:27:52,00:06:57,2009-01-01 09:34:49,2,00:00:00,2009-01-01 09:34:49,00:04:13,2009-01-01 09:39:02,00:19:32
15,16,2009-01-01 09:28:11,B,00:00:50,2009-01-01 09:29:01,00:04:45,2009-01-01 09:33:46,3,00:18:26,2009-01-01 09:52:12,00:10:18,2009-01-01 10:02:30,00:34:19
16,17,2009-01-01 09:30:03,A,00:00:00,2009-01-01 09:30:03,00:06:36,2009-01-01 09:36:39,1,00:02:23,2009-01-01 09:39:02,00:09:07,2009-01-01 09:48:09,00:18:06
17,18,2009-01-01 09:30:35,C,00:03:11,2009-01-01 09:33:46,00:04:24,2009-01-01 09:38:10,3,00:31:00,2009-01-01 10:09:10,00:04:41,2009-01-01 10:13:51,00:43:16
18,19,2009-01-01 09:31:12,A,00:03:37,2009-01-01 09:34:49,00:03:22,2009-01-01 09:38:11,2,00:09:58,2009-01-01 09:48:09,00:06:20,2009-01-01 09:54:29,00:23:17
19,20,2009-01-01 09:31:13,C,00:05:26,2009-01-01 09:36:39,00:03:53,2009-01-01 09:40:32,1,00:33:19,2009-01-01 10:13:51,00:08:55,2009-01-01 10:22:46,00:51:33
20,21,2009-01-01 09:32:20,B,00:05:50,2009-01-01 09:38:10,00:04:23,2009-01-01 09:42:33,3,00:19:57,2009-01-01 10:02:30,00:09:15,2009-01-01 10:11:45,00:39:25
21,22,2009-01-01 09:33:46,A,00:04:25,2009-01-01 09:38:11,00:06:46,2009-01-01 09:44:57,2,00:09:32,2009-01-01 09:54:29,00:09:12,2009-01-01 10:03:41,00:29:55
22,23,2009-01-01 09:35:13,A,00:05:19,2009-01-01 09:40:32,00:06:25,2009-01-01 09:46:57,1,00:16:44,2009-01-01 10:03:41,00:08:41,2009-01-01 10:12:22,00:37:09
23,24,2009-01-01 09:35:56,B,00:06:37,2009-01-01 09:42:33,00:03:44,2009-01-01 09:46:17,3,00:25:28,2009-01-01 10:11:45,00:10:28,2009-01-01 10:22:13,00:46:17
24,25,2009-01-01 09:36:17,A,00:08:40,2009-01-01 09:44:57,00:05:43,2009-01-01 09:50:40,2,00:21:42,2009-01-01 10:12:22,00:10:39,2009-01-01 10:23:01,00:46:44
25,26,2009-01-01 09:37:01,C,00:09:16,2009-01-01 09:46:17,00:04:05,2009-01-01 09:50:22,3,00:32:24,2009-01-01 10:22:46,00:03:46,2009-01-01 10:26:32,00:49:31
26,27,2009-01-01 09:40:50,B,00:06:07,2009-01-01 09:46:57,00:06:19,2009-01-01 09:53:16,1,00:28:57,2009-01-01 10:22:13,00:06:52,2009-01-01 10:29:05,00:48:15
27,28,2009-01-01 09:41:38,A,00:08:44,2009-01-01 09:50:22,00:03:59,2009-01-01 09:54:21,3,00:28:40,2009-01-01 10:23:01,00:09:04,2009-01-01 10:32:05,00:50:27
28,29,2009-01-01 09:42:44,A,00:07:56,2009-01-01 09:50:40,00:04:59,2009-01-01 09:55:39,2,00:36:26,2009-01-01 10:32:05,00:09:07,2009-01-01 10:41:12,00:58:28
29,30,2009-01-01 09:48:35,B,00:04:41,2009-01-01 09:53:16,00:04:58,2009-01-01 09:58:14,1,00:30:51,2009-01-01 10:29:05,00:05:21,2009-01-01 10:34:26,00:45:51
30,31,2009-01-01 09:48:53,A,00:05:28,2009-01-01 09:54:21,00:04:45,2009-01-01 09:59:06,3,00:42:06,2009-01-01 10:41:12,00:10:31,2009-01-01 10:51:43,01:02:50
31,32,2009-01-01 09:50:17,B,00:05:22,2009-01-01 09:55:39,00:05:48,2009-01-01 10:01:27,2,00:32:59,2009-01-01 10:34:26,00:09:10,2009-01-01 10:43:36,00:53:19
32,33,2009-01-01 09:50:34,A,00:07:40,2009-01-01 09:58:14,00:06:59,2009-01-01 10:05:13,1,00:46:30,2009-01-01 10:51:43,00:11:13,2009-01-01 11:02:56,01:12:22
33,34,2009-01-01 09:50:45,A,00:08:21,2009-01-01 09:59:06,00:05:59,2009-01-01 10:05:05,3,00:57:51,2009-01-01 11:02:56,00:08:05,2009-01-01 11:11:01,01:20:16
34,35,2009-01-01 09:51:12,A,00:10:15,2009-01-01 10:01:27,00:06:32,2009-01-01 10:07:59,2,01:03:02,2009-01-01 11:11:01,00:10:48,2009-01-01 11:21:49,01:30:37
35,36,2009-01-01 10:02:52,A,00:02:13,2009-01-01 10:05:05,00:04:19,2009-01-01 10:09:24,3,01:12:25,2009-01-01 11:21:49,00:11:28,2009-01-01 11:33:17,01:30:25
36,37,2009-01-01 10:03:38,C,00:01:35,2009-01-01 10:05:13,00:06:33,2009-01-01 10:11:46,1,00:14:46,2009-01-01 10:26:32,00:07:35,2009-01-01 10:34:07,00:30:29
37,38,2009-01-01 10:06:12,A,00:01:47,2009-01-01 10:07:59,00:04:20,2009-01-01 10:12:19,2,01:20:58,2009-01-01 11:33:17,00:10:07,2009-01-01 11:43:24,01:37:12
38,39,2009-01-01 10:07:04,C,00:02:20,2009-01-01 10:09:24,00:03:38,2009-01-01 10:13:02,3,00:21:05,2009-01-01 10:34:07,00:10:28,2009-01-01 10:44:35,00:37:31
39,40,2009-01-01 10:08:33,C,00:03:13,2009-01-01 10:11:46,00:05:15,2009-01-01 10:17:01,1,00:27:34,2009-01-01 10:44:35,00:04:53,2009-01-01 10:49:28,00:40:55
40,41,2009-01-01 10:08:54,C,00:03:25,2009-01-01 10:12:19,00:03:59,2009-01-01 10:16:18,2,00:33:10,2009-01-01 10:49:28,00:09:51,2009-01-01 10:59:19,00:50:25
41,42,2009-01-01 10:10:17,C,00:02:45,2009-01-01 10:13:02,00:03:37,2009-01-01 10:16:39,3,00:42:40,2009-01-01 10:59:19,00:09:10,2009-01-01 11:08:29,00:58:12
42,43,2009-01-01 10:11:03,B,00:05:15,2009-01-01 10:16:18,00:06:41,2009-01-01 10:22:59,2,00:20:37,2009-01-01 10:43:36,00:08:09,2009-01-01 10:51:45,00:40:42
43,44,2009-01-01 10:18:12,A,00:00:00,2009-01-01 10:18:12,00:05:29,2009-01-01 10:23:41,1,01:19:43,2009-01-01 11:43:24,00:05:37,2009-01-01 11:49:01,01:30:49
44,45,2009-01-01 10:19:20,C,00:00:00,2009-01-01 10:19:20,00:04:12,2009-01-01 10:23:32,3,00:44:57,2009-01-01 11:08:29,00:12:21,2009-01-01 11:20:50,01:01:30
45,46,2009-01-01 10:23:08,B,00:00:00,2009-01-01 10:23:08,00:05:06,2009-01-01 10:28:14,2,00:23:31,2009-01-01 10:51:45,00:08:49,2009-01-01 11:00:34,00:37:26
46,47,2009-01-01 10:23:30,C,00:00:02,2009-01-01 10:23:32,00:06:54,2009-01-01 10:30:26,3,00:50:24,2009-01-01 11:20:50,00:09:11,2009-01-01 11:30:01,01:06:31
47,48,2009-01-01 10:24:26,B,00:00:00,2009-01-01 10:24:26,00:04:33,2009-01-01 10:28:59,1,00:31:35,2009-01-01 11:00:34,00:06:46,2009-01-01 11:07:20,00:42:54
48,49,2009-01-01 10:27:17,B,00:00:57,2009-01-01 10:28:14,00:04:17,2009-01-01 10:32:31,2,00:34:49,2009-01-01 11:07:20,00:05:29,2009-01-01 11:12:49,00:45:32
49,50,2009-01-01 10:28:28,B,00:00:31,2009-01-01 10:28:59,00:05:33,2009-01-01 10:34:32,1,00:38:17,2009-01-01 11:12:49,00:07:19,2009-01-01 11:20:08,00:51:40